spring.application.name=analytic-service
server.port=8082

info.service.name=Analytic Service
info.service.description=Analytics service for collecting, processing, and analyzing application data to generate meaningful insights.
