spring.application.name=api-management-service
server.port=8081

info.service.name= API Management Service
info.service.description= Management Service for users, routes and gateway policies

spring.datasource.url=jdbc:mysql://localhost:3306/gatekeeper_management
spring.datasource.username=root
spring.datasource.password=Harshdeep@2003

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

